version: "3"

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1001
      - USER_GID=1001
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitea.rule=Host(`gitea.utkarsh.cloudns.asia`)
      - traefik.http.routers.gitea.entrypoints=websecure
      - traefik.http.routers.gitea.tls=true
      - traefik.http.routers.gitea.tls.certresolver=ca
      - traefik.http.services.gitea.loadbalancer.server.port=3000
    volumes:
      - ./storage/gitea-volume:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    # ports:
    #   - "127.0.0.1:2222:22"

  registry:
    container_name: registry
    restart: always
    image: registry:2
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Fuck Realm
      REGISTRY_STORAGE_DELETE_ENABLED: true
    labels:
      - traefik.enable=true
      - traefik.http.routers.registry.rule=Host(`registry.utkarsh.cloudns.asia`)
      - traefik.http.routers.registry.entrypoints=websecure
      - traefik.http.routers.registry.tls=true
      - traefik.http.routers.registry.tls.certresolver=ca
    volumes:
      - ./storage/registry-volume/auth:/auth
      - ./storage/registry-volume/storage:/var/lib/registry

  portainer:
    container_name: portainer
    restart: always
    image: portainer/portainer-ee:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`portainer.utkarsh.cloudns.asia`)
      - traefik.http.routers.portainer.entrypoints=websecure
      - traefik.http.routers.portainer.tls=true
      - traefik.http.routers.portainer.tls.certresolver=ca
      - traefik.http.services.portainer.loadbalancer.server.port=9000
    volumes:
      - ./storage/portainer-volume:/data

  traefik:
    image: traefik:latest
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./storage/traefik-volume/acme.json:/acme.json
      - ./storage/traefik-volume/dynamic_config.toml:/dynamic/traefik.toml
      - ./storage/traefik-volume/static_config.toml:/traefik.toml

  jenkins:
    build:
      context: ./storage/jenkins-volume/service
      args:
          HOST_UID: 1001
          HOST_GID: 999
    restart: unless-stopped
    container_name: jenkins
    environment:
      - "JAVA_OPTS=-Xmx3g -Xms2G"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./storage/jenkins-volume/storage:/var/jenkins_home
    labels:
      - traefik.enable=true
      - traefik.http.routers.jenkins.rule=Host(`jenkins.utkarsh.cloudns.asia`)
      - traefik.http.routers.jenkins.entrypoints=websecure
      # - traefik.http.routers.jenkins.middlewares=simpleAuth@file
      - traefik.http.routers.jenkins.tls=true
      - traefik.http.routers.jenkins.tls.certresolver=ca
      - traefik.http.services.jenkins.loadbalancer.server.port=8080

networks:
  default:
    name: web
